### ISSUE TITLE
CompilationException: Back-end: Please report this problem https://kotl.in/issue

### ISSUE THREAD

**Issue by ryanw-mobile** [ryanw-mobile/OctoMeter#311]
Right now the current dependency versions can only build on Android - 
Kotlin compiler error for iOS and Desktop.

Probably we are hitting some unknown JetBrains bugs which we should downgrade something in order to build our upcoming release

**Comment by ryanw-mobile** [comment]
Got this error using Kotlin 2.0.20 and Compose Multiplatform. After a lot of investigation I found the problem to be a missing actual implementation. This error message was not very helpful though.

Edit: Sorry for formatting. Got borked after one copy paste too many, and the original is long gone. =/

org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
https://youtrack.jetbrains.com/issue/KT-71161

**Comment by ryanw-mobile** [comment]
```
e: org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
/Users/rwong/Documents/StudioProjects/Roctopus/composeApp/build/generated/source/apollo/service/com/rwmobi/kunigami/graphql/EnergyProductsQuery.kt:-1:-1
Details: Internal error in file lowering: java.lang.IllegalStateException: should not be called
        at org.jetbrains.kotlin.utils.addToStdlib.AddToStdlibKt.shouldNotBeCalled(addToStdlib.kt:323)
        at org.jetbrains.kotlin.utils.addToStdlib.AddToStdlibKt.shouldNotBeCalled$default(addToStdlib.kt:322)
        at org.jetbrains.kotlin.ir.symbols.impl.IrFakeOverrideSymbolBase.getOwner(IrFakeOverrideSymbol.kt:41)
        at org.jetbrains.kotlin.ir.symbols.impl.IrFakeOverrideSymbolBase.getOwner(IrFakeOverrideSymbol.kt:20)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitMemberAccess(ExternalPackageParentPatcherLowering.kt:39)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionAccess(IrElementVisitorVoid.kt:240)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitFunctionAccess(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:360)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitCall(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:356)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitCall(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitCall(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.acceptChildren(IrBranch.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBranch(IrElementVisitorVoid.kt:688)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitBranch(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitElseBranch(IrElementVisitorVoid.kt:696)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElseBranch(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitElseBranch(IrElementVisitorVoid.kt:692)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElseBranch(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElseBranch(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.expressions.IrElseBranch.accept(IrElseBranch.kt:19)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.acceptChildren(IrWhen.kt:27)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:192)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitExpression(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitWhen(IrElementVisitorVoid.kt:680)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitWhen(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitWhen(IrElementVisitorVoid.kt:676)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitWhen(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitWhen(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.acceptChildren(IrMemberAccessExpression.kt:62)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitMemberAccess(ExternalPackageParentPatcherLowering.kt:38)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionAccess(IrElementVisitorVoid.kt:240)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitFunctionAccess(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:360)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitCall(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:356)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitCall(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitCall(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrSetValue.acceptChildren(IrSetValue.kt:24)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:192)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitExpression(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclarationReference(IrElementVisitorVoid.kt:224)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitDeclarationReference(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitValueAccess(IrElementVisitorVoid.kt:640)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitValueAccess(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSetValue(IrElementVisitorVoid.kt:656)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitSetValue(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSetValue(IrElementVisitorVoid.kt:652)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitSetValue(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitSetValue(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.expressions.IrSetValue.accept(IrSetValue.kt:21)
        at org.jetbrains.kotlin.ir.expressions.IrBlockBody.acceptChildren(IrBlockBody.kt:23)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBody(IrElementVisitorVoid.kt:200)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitBody(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:216)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitBlockBody(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:212)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitBlockBody(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitBlockBody(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:20)
        at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:50)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitDeclaration(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:72)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitFunction(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:144)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitSimpleFunction(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:140)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitSimpleFunction(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitSimpleFunction(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:39)
        at org.jetbrains.kotlin.ir.declarations.IrClass.acceptChildren(IrClass.kt:76)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitDeclaration(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:48)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitClass(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitClass(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitClass(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
        at org.jetbrains.kotlin.ir.declarations.IrClass.acceptChildren(IrClass.kt:76)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitDeclaration(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:48)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitClass(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitClass(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitClass(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
        at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitElement(ExternalPackageParentPatcherLowering.kt:34)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:168)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitPackageFragment(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:184)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitFile(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:180)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitFile(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering$Visitor.visitFile(ExternalPackageParentPatcherLowering.kt:32)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:28)
        at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
        at org.jetbrains.kotlin.backend.jvm.lower.ExternalPackageParentPatcherLowering.lower(ExternalPackageParentPatcherLowering.kt:28)
        at org.jetbrains.kotlin.backend.common.FileLoweringPass.lower(Lower.kt:42)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt.makeIrModulePhase$lambda$5(PhaseBuilders.kt:110)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$createSimpleNamedCompilerPhase$1.phaseBody(PhaseBuilders.kt:69)
        at org.jetbrains.kotlin.backend.common.phaser.SimpleNamedCompilerPhase.phaseBody(CompilerPhase.kt:226)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:20)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:14)
        at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.phaseBody(CompilerPhase.kt:166)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:62)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.invokeLowerings(JvmIrCodegenFactory.kt:358)
        at org.jetbrains.kotlin.codegen.CodegenFactory.generateModule(CodegenFactory.kt:46)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModuleInFrontendIRMode(JvmIrCodegenFactory.kt:433)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.generateCodeFromIr(jvmCompilerPipeline.kt:246)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.compileModulesUsingFrontendIrAndLightTree(jvmCompilerPipeline.kt:142)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:148)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:43)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:464)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:73)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:506)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:423)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:301)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:675)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:92)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1660)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: should not be called
        ... 165 more

```

The Android app runs without issues. 
While the error points to the Apollo Kotlin generated code, but I believe that's caused by Room Multiplatform/KSP as the workaround already exists in my CI pipeline for building the app on Github.

I believe it is something to do with the KSP.

For Desktop App:
```
./gradlew clean
./gradlew run
```
Will produce the CompilationException like above.

However,
```
./gradlew clean
./gradlew :composeApp:kspCommonMainKotlinMetadata 
./gradlew run
```
The desktop app starts properly.

**Comment by ryanw-mobile** [comment]
We don't want to waste time on this. 
Since we have a local workaround, this issue will not affect us.

We will keep this ticket here as a reference.
